package com.gspb.avalon.document.application.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

/**
 * Command for generating a document.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GenerateDocumentCommand {
    
    @NotNull(message = "Document ID is required")
    private UUID documentId;
    
    @NotBlank(message = "Content URL is required")
    private String contentUrl;
    
    @NotBlank(message = "Generated by is required")
    private String generatedBy;
}
