spring.application.name=client-service
server.port=8081
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry.avalon.local:8761/eureka/}
